server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Configuração para listar os arquivos da pasta roms em JSON
    location /roms/ {
        autoindex on;
        autoindex_format json;
    }
}